[project]
name = "cifar100-speedrun"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pillow",
    "pyarrow",
    "setuptools>=82.0.1",
    "torch==2.4.0+cu124",
    "torchvision==0.19.0+cu124",
    "triton==3.0.0",
]

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }
